baseurl = "http://blog.omdesign.cz/"
contentdir = "./content"
languageCode = "cs-cz"
title = "blog.omdesign.cz"
publishdir = "./docs"
canonifyurls = true
googleAnalytics = "UA-5420131-1"
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableEmoji = true

[params]
Description = "aaa"

[author]
name = "Roman Ožana"
email = "ozana@omdesign.cz"

[taxonomies]
tag = "tags"

[permalinks]
posts = "/:slug/"
pages = "/:slug/"
recepty = "/:section/:slug/"
