baseurl = "http://blog.omdesign.cz/"
contentdir = "./content"
languageCode = "cs-cz"
title = "blog.omdesign.cz"
publishdir = "./docs"
canonifyurls = true
googleAnalytics = "UA-123-45"

ignoreFiles = [ "readme.md" ]
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableEmoji = true

[author]
name = "Roman Ožana"
email = "ozana@omdesign.cz"

[taxonomies]
tag = "tags"

[permalinks]
posts = "/:slug/"
pages = "/:slug/"
recepty = "/:section/:slug/"
