baseurl = "http://blog.omdesign.cz"
contentdir = "./content"
languageCode = "cs-cz"
title = "Blog omdesign.cz"
publishdir = "./public"
canonifyurls = true
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableEmoji = true

[params]
Description = "This is page description"
Months = ["Leden", "Únor", "Březen", "Duben", "Květen", "Červen", "Červenec" ,"Srpen" ,"Září" , "Říjen" , "Listopad" , "Prosinec"]

[author]
name = "Roman Ožana"
email = "ozana@omdesign.cz"

[taxonomies]
tag = "tags"

[permalinks]
posts = "/:slug/"
pages = "/:slug/"
recepty = "/:section/:slug/"
